name: WinPyInstaller

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Step 1 - Create a temporary artifact downloads folder
      run: mkdir downloads

    - uses: actions/checkout@v1
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PySide2
        pip install pyinstaller

    - name: build with pyinstaller
      run: |
        pyinstaller calculator.py
        
    #- name: Step 3 - Use the Upload Artifact GitHub Action
    - uses: actions/upload-artifact@v2.2.4
      with: 
        name: assets-for-download
        path: downloads
